# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DateTime-Format-WindowsFileTime
version:      0.01
version_from: lib/DateTime/Format/WindowsFileTime.pm
installdirs:  site
requires:
    DateTime:                      0.25
    Math::BigInt:                  1.70

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
